name: Terraform CI/CD

env:
  TF_CLOUD_ORGANIZATION: "Cloud-Organization"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Iman-Renner-AWS-cloud-resume-env"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Trigger Terraform Cloud Run
      if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
      run: |
        curl -s -X POST \
          --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --data '{
            "data": {
              "attributes": {
                "is-destroy":false,
                "message": "Triggered by GitHub Actions"
              },
              "type":"runs",
              "relationships": {
                "workspace": {
                  "data": {
                    "type": "workspaces",
                    "id": "${{ env.TF_WORKSPACE }}"
                  }
                }
              }
            }
          }' \
          https://app.terraform.io/api/v2/organizations/${{ env.TF_CLOUD_ORGANIZATION }}/workspaces/${{ env.TF_WORKSPACE }}/runs