name: Lambda CI/CD

on:
  push:
    paths:
      - 'backend_infrastructure/Lambda Folder/lambda_function.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r '${{ github.workspace }}/backend_infrastructure/Lambda Folder/requirements.txt'
        pip install pytest moto
    - name: Run tests
      env:
        AWS_DEFAULT_REGION: us-east-1
      run: |
        cd '${{ github.workspace }}/backend_infrastructure/Lambda Folder'
        pytest test_lambda_function.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy to Lambda
      run: |
        cd '${{ github.workspace }}/backend_infrastructure/Lambda Folder'
        zip -j function.zip lambda_function.py
        aws lambda update-function-code --function-name VisitorCounterFunction --zip-file fileb://function.zip
